### ISSUE TITLE
Q: What is equivalent to PostAndReply

### ISSUE THREAD

**Issue by goldfish1974** [fsprojects/Cricket#47]
Hi,

This is a bit of a Noob question. I'm just starting out in F# and Agents.

How would I go about doing a PostAndReply type agent request.

Your tracing sample seems to post back a message to the "source" agent as another "Request", but that doesn't address a situation where the request is not coming from an existing Agent.

e.g  Make a call that originated from somewhere other than within an Agent, say, a command line helper tool that makes a remote Agent request into a larger system (perhaps running as a service). I presume I need to use Message.Post or "agent" <-- XXXX calls to get the Message into the worker.

Also, how would I go about making a call to another agent such that:  let! result = Message.PostAndReply(parms * ReplyChannel) was possible, and I wouldn't need to manage the state during the recursive call within the worker function. (One of the other examples seems to maintain a map so that the request/reply messages between agents can be linked together. This seems rather un-async to me...or have I totally missed something with how I should be using Cricket?

Thanks for any info you can share.
Regards,
Nathan

**Comment by goldfish1974** [comment]
I've found your reply to Issue #36, and I think that answers my question, except in the situation of via remote requests from the Agent.

Does the AsyncResultCell work via a remote Agent request also?

Thanks in advance.

P.S. I should have searched the closed issues first...sorry :-/

**Comment by colinbull** [comment]
No problem, I really should monitor the issues more closely. 

Currently if you need an explicit reply, then you can use `Messge.reply` in your message handler. This will return the reply asynchronously back to the agent. There is an example of this in the PingPong example [here](https://github.com/fsprojects/Cricket/blob/master/src/Samples/Remoting/PingPong/PongNode/Program.fs#L18). If you want to do this synchronously then it is still possible, Although somewhat more complicated. 

Basically you'll want something like the following

     let replyAwaiters = new ConcurrentQueue<Guid, AsyncResultCell<'a>>()
     actor {
        body(
               let replyAwaiters = new ConcurrentQueue<Guid, AsyncResultCell<'a>>()
               let rec loop() = messageHandler { 
                    let! msg = Message.scan (fun msg -> 
                                         match replayAwaiters.TryPeek() with
                                         | true, replyCell when msg.Message.Id = (fst replyCell) -> 
                                                Some async { 
                                                    let! msg = replayAwaiters.Dequeue() 
                                                    (snd msg).SetResult(msg.Message) }
                                         | _, _ -> None)
                       return! loop()} 
               loop())
     }

*Disclaimer* - No compiler at hand so haven't checked this.

So, the basic idea is to have a queue which stores the `AsyncResultCell` along with the message Id, then scan the queue only accepting the message the that matches the top awaiter. If it does then handle that message and rescan the queue for the next awaiter. 

I do plan on surfacing this in a far more friendly way in the API, however using this it is quite easy to create situation where either an `OutOfMemoryException` looms, because you never handle messages, or the cost of handling the msg vs doing the scan, is so different that your app spends more time scanning for messages than actually processing them. For this reason this is why I prefer the asynchronous method, given initially.

Let me know if this helps

Cheers.

**Comment by goldfish1974** [comment]
Thanks for the feedback. The Message.reply works well.

I found a different way to do the synchronous call. This seems to work fairly well for things like a command line tool that sends the message off, and waits for the result:

    let handleAsync msg =
        async {
            let resultCell = new AsyncResultCell<_>()
            agent <-- msg(resultCell)
            return! resultCell.AwaitResult()
        } |> Async.RunSynchronously

I'm having trouble with the remote agents though. I'll open another question on that, since it's different enough to this (assuming I cannot find the answer in closed issues :)

Thanks for your help.
